server:
  port: 7799
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:7776/eureka
  instance:
    #    表示client发送心跳给server端的频率
    lease-renewal-interval-in-seconds: 2
    #    表示server至上次收到client的心跳之后，等待下一次心跳的超时时间，超时则移除
    lease-expiration-duration-in-seconds: 2

    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: dm-order-consumer
  rabbitmq:
    host: 192.168.174.130
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 192.168.174.130
    port: 6379
    user: root
    password: 123456
    timeout: 3000